package com.ecpss.vo;

import java.util.Date;

/**
 * InternationalHuakuan generated by MyEclipse Persistence Tools
 */

public class WebInternationalHuakuan implements java.io.Serializable {
	private Long merchChnal; // 商户通道
	private Long rateID;
	// Fields

	private Long id;

	private Long merchantno;

	private Long batchno;

	private Double ordercount = 0d;

	private String trademoneyname;

	private Double refundmentmoney = 0d;

	private Double protestmoney = 0d;

	private Double procedurefee = 0d;

	private String balancemoneyname;

	private Double balancemoney = 0d;

	private Date huakuantime;

	private String huakuanbankname;

	private Date createtabletime;

	private String remark;

	private Double freezecount = 0d;
	/**
	 * 未划款退款拒付笔数
	 */
	private int refuce; 
	/**
	 * 未划款退款拒付(退款部分)的金额	
	 */
	private Double refuceMoney = 0d; 
	/**
	 * 未划款退款拒付(交易部分)的金额
	 */
	private Double refuceMoneyAll=0d;// 	
	/**
	 * 已划款退款拒付
	 */
	private int refuceComplement;//
	/**
	 * 已划款退款拒付金额（退款部分）金额
	 */
	private Double refuceComplementMoney=0d;//
	/**
	 * 已划款退款拒付金额（交易部分）金额
	 */
	private Double refuceComplementMoneyAll=0d;//
	/**
	 * 成功交易笔数
	 */
	private int tradeNumber; // 
	/**
	 * 成功交易金额
	 */
	private Double tradeMoney = 0d; // 
	/**
	 * ]未结算交易笔数
	 */
	private int tradeNumberAll; // 
	/**
	 * 未结算交易金额
	 */
	private Double tradeMoneyAll = 0d; // 
	/**
	 * 未结算本期部分退款笔数
	 */
	private int noTuikuanNumber; // 
	/**
	 * 未结算本期部分退款金额
	 */
	private Double noTuiKuanMoney = 0d;
	/**
	 * 未结算本期全额退款笔数
	 */
	private int noTuikuanNumberall; // 
	/**
	 * 未结算本期全额退款金额
	 */
	private Double noTuiKuanMoneyall = 0d; // 
	/**
	 * 已结算本期退款金额
	 */
	private Double tuiKuanMoney = 0d; // 
	/**
	 * 已结算本期退款笔数
	 */
	private int tuiKuanNumber; // 
	
	/**
	 * 已结算本期部分退款金额
	 */
	private Double tuiKuanMoneyall = 0d; // 
	/**
	 * 已结算本期全部退款笔数
	 */
	private int tuiKuanNumberall; // 
	/**
	 * 已结算本期冻结金额
	 */
	private Double freezeMoney = 0d; // 
	/**
	 * 已结算本期冻结笔数
	 */
	private int freezeNumber; // 
	/**
	 * 解冻交易金额
	 */
	private Double thawMoney = 0d; // 
	/**
	 * 解冻交易笔数
	 */
	private int thawNumber; // 
	/**
	 * 未划款解冻交易金额
	 */
	private Double nothawMoney = 0d; // 
	/**
	 * 未划款解冻交易笔数	
	 */
	private int nothawNumber; // 
	/**
	 * 已划款解冻交易金额
	 */
	private Double yesthawMoney = 0d; // 
	/**
	 * 已划款解冻交易笔数
	 */
	private int yesthawNumber; // 		
	/**
	 * 已结算本期拒付金额
	 */
	private Double protestMoney = 0d; // 
	/**
	 * 已结算本期拒付笔数
	 */
	private int protestNumber; // 
	/**
	 * 未结算本期拒付金额
	 */
	private Double noProtestMoney = 0d; // 
	/**
	 * 未结算本期拒付笔数
	 */
	private int noProtestNumber; // 
	/**
	 * 手续费率
	 */
	private Double procedureRate = 0d; // 
	/**
	 * 拒付处理费
	 */
	private Double protestFee = 0d; // 
	/**
	 * 手续费
	 */
	private Double procedureFee = 0d; // 
	/**
	 * 保证金金额
	 */
	private Double bailmoney = 0d; // 
	/**
	 * 保证金费率
	 */
	private Double bailrate = 0d; // 
	/**
	 *  手续费定额
	 */
	private Double proceFeeRation = 0d; //
	/**
	 * 交易币种名称
	 */
	private String tradeMoneykindName; // 
	/**
	 * 结算汇率
	 */
	private Double balancerate = 0d; // 
	/**
	 * 通道
	 */
	private String channels; // 
	/**
	 * 结算汇率日期
	 */
	private Date exchangedate; // 
	/**
	 * 结算当天的汇率(计算拒付处理费的时候用)
	 */
	private Double nowBalanceRate = 0d; // 
	/**
	 * 每个汇率对应的RMB金额
	 */
	private Double rmbmoney = 0d; // 
	
	

	// Constructors

	/** default constructor */
	public WebInternationalHuakuan() {
	}

	/** minimal constructor */
	public WebInternationalHuakuan(Long id) {
		this.id = id;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getMerchantno() {
		return this.merchantno;
	}

	public void setMerchantno(Long merchantno) {
		this.merchantno = merchantno;
	}

	public Long getBatchno() {
		return this.batchno;
	}

	public void setBatchno(Long batchno) {
		this.batchno = batchno;
	}

	public Double getOrdercount() {
		return this.ordercount;
	}

	public void setOrdercount(Double ordercount) {
		this.ordercount = ordercount;
	}

	public String getTrademoneyname() {
		return this.trademoneyname;
	}

	public void setTrademoneyname(String trademoneyname) {
		this.trademoneyname = trademoneyname;
	}

	public Double getRefundmentmoney() {
		return this.refundmentmoney;
	}

	public void setRefundmentmoney(Double refundmentmoney) {
		this.refundmentmoney = refundmentmoney;
	}

	public Double getProtestmoney() {
		return this.protestmoney;
	}

	public void setProtestmoney(Double protestmoney) {
		this.protestmoney = protestmoney;
	}

	/*
	 * （本期结算交易总额-未结算本期退款-未结算本期拒付+未划款退款拒付（退款额）
	 * -已结算本期退款-已结算本期拒付+已划款退款拒付（退款额））*保证金率
	 */
	public Double getBailmoney() {
    
      // this.bailmoney =(this.getTradeMoneyAll()-this.getNoTuiKuanMoney()-this.getNoProtestMoney()+this.refuceMoney-tuiKuanMoney-tuiKuanMoneyall+this.getRefuceComplementMoney())*bailrate;
       this.bailmoney =(this.getTradeMoneyAll()
    		   -this.getNoTuiKuanMoney()
    		   -this.getNoTuiKuanMoneyall()
    		   -this.getNoProtestMoney()
    		   +this.refuceMoney-tuiKuanMoney-tuiKuanMoneyall
    		   -this.protestMoney
    		   +this.getRefuceComplementMoney())*bailrate;
       
       System.out.println("保证金---"+this.getTradeMoneyAll()+"---"+this.getNoTuiKuanMoney()
    		   +"---"+this.getNoTuiKuanMoneyall()
    		   +"---"+this.getNoProtestMoney()
    		   +"---"+(this.refuceMoney-tuiKuanMoney-tuiKuanMoneyall)+"---"+this.protestMoney
    		   +"---"+this.getRefuceComplementMoney());
       
       return this.bailmoney;
	}

	public void setBailmoney(Double bailmoney) {
		this.bailmoney = bailmoney;
	}

	/*
	 * 本期结算交易*手续费率
	 * 
	 */
	public Double getProcedurefee() {
		return this.procedurefee;

	}

	public void setProcedurefee(Double procedurefee) {
		this.procedurefee = procedurefee;
	}

	public String getBalancemoneyname() {
		return this.balancemoneyname;
	}

	public void setBalancemoneyname(String balancemoneyname) {
		this.balancemoneyname = balancemoneyname;
	}

	public Double getBalancemoney() {
		return  ( this.getTradeMoneyAll()-this.getNoTuiKuanMoney()-this.getNoTuiKuanMoneyall()-this.getTuiKuanMoney()-this.getTuiKuanMoneyall()-this.getFreezeMoney()+this.getThawMoney()-this.getNoProtestMoney()-this.getProtestMoney()-this.getBailmoney()-this.getProcedureFee());
	}

	public void setBalancemoney(Double balancemoney) {
		this.balancemoney = balancemoney;
	}

	public Date getHuakuantime() {
		return this.huakuantime;
	}

	public void setHuakuantime(Date huakuantime) {
		this.huakuantime = huakuantime;
	}

	public String getHuakuanbankname() {
		return this.huakuanbankname;
	}

	public void setHuakuanbankname(String huakuanbankname) {
		this.huakuanbankname = huakuanbankname;
	}

	public Date getCreatetabletime() {
		return this.createtabletime;
	}

	public void setCreatetabletime(Date createtabletime) {
		this.createtabletime = createtabletime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Double getFreezecount() {
		return this.freezecount;
	}

	public void setFreezecount(Double freezecount) {
		this.freezecount = freezecount;
	}

	public Double getBailrate() {
		return bailrate;
	}

	public void setBailrate(Double bailrate) {
		this.bailrate = bailrate;
	}

	public Double getBalancerate() {
		return balancerate;
	}

	public void setBalancerate(Double balancerate) {
		this.balancerate = balancerate;
	}

	public String getChannels() {
		return channels;
	}

	public void setChannels(String channels) {
		this.channels = channels;
	}

	public Double getFreezeMoney() {
		return freezeMoney;
	}

	public void setFreezeMoney(Double freezeMoney) {
		this.freezeMoney = freezeMoney;
	}

	public int getFreezeNumber() {
		return freezeNumber;
	}

	public void setFreezeNumber(int freezeNumber) {
		this.freezeNumber = freezeNumber;
	}

	public Double getNoProtestMoney() {
		return noProtestMoney;
	}

	public void setNoProtestMoney(Double noProtestMoney) {
		this.noProtestMoney = noProtestMoney;
	}

	public int getNoProtestNumber() {
		return noProtestNumber;
	}

	public void setNoProtestNumber(int noProtestNumber) {
		this.noProtestNumber = noProtestNumber;
	}
	//手续费   本期结算交易*手续费率
	public Double getProcedureFee() {

		return this.getTradeMoneyAll()*procedureRate;
	}

	public void setProcedureFee(Double procedureFee) {

		this.procedureFee = procedureFee;
	}

	public Double getProcedureRate() {
		return procedureRate;
	}

	public void setProcedureRate(Double procedureRate) {
		this.procedureRate = procedureRate;
	}

	public Double getProceFeeRation() {
		return proceFeeRation;
	}

	public void setProceFeeRation(Double proceFeeRation) {
		this.proceFeeRation = proceFeeRation;
	}
//（未划款拒付+已划款拒付）*20 
	public Double getProtestFee() {
		return Double.valueOf((this.protestNumber+this.noProtestNumber)*20);
	}

	public void setProtestFee(Double protestFee) {
		this.protestFee = protestFee;
	}

	public Double getProtestMoney() {
		return protestMoney;
	}

	public void setProtestMoney(Double protestMoney) {
		this.protestMoney = protestMoney;
	}

	public int getProtestNumber() {
		return protestNumber;
	}

	public void setProtestNumber(int protestNumber) {
		this.protestNumber = protestNumber;
	}

	public Double getThawMoney() {
		return  (nothawMoney+yesthawMoney);
	}

	public void setThawMoney(Double thawMoney) {
		this.thawMoney = thawMoney;
	}

	public int getThawNumber() {
		return (nothawNumber+yesthawNumber);
	}

	public void setThawNumber(int thawNumber) {
		this.thawNumber = thawNumber;
	}

	public String getTradeMoneykindName() {
		return tradeMoneykindName;
	}

	public void setTradeMoneykindName(String tradeMoneykindName) {
		this.tradeMoneykindName = tradeMoneykindName;
	}

	public Double getNoTuiKuanMoney() {
		return noTuiKuanMoney;
	}

	public void setNoTuiKuanMoney(Double noTuiKuanMoney) {
		this.noTuiKuanMoney = noTuiKuanMoney;
	}

	public int getNoTuikuanNumber() {
		return noTuikuanNumber;
	}

	public void setNoTuikuanNumber(int noTuikuanNumber) {
		this.noTuikuanNumber = noTuikuanNumber;
	}

	public int getTradeNumber() {
		return tradeNumber;
	}

	public void setTradeNumber(int tradeNumber) {
		this.tradeNumber = tradeNumber;
	}

	public Double getTradeMoney() {
		return tradeMoney;
	}

	public void setTradeMoney(Double tradeMoney) {
		this.tradeMoney = tradeMoney;
	}

	public Double getTuiKuanMoney() {
		return tuiKuanMoney;
	}

	public void setTuiKuanMoney(Double tuiKuanMoney) {
		this.tuiKuanMoney = tuiKuanMoney;
	}

	public int getTuiKuanNumber() {
		return tuiKuanNumber;
	}

	public void setTuiKuanNumber(int tuiKuanNumber) {
		this.tuiKuanNumber = tuiKuanNumber;
	}

	public Date getExchangedate() {
		return exchangedate;
	}

	public void setExchangedate(Date exchangedate) {
		this.exchangedate = exchangedate;
	}

	public Double getNowBalanceRate() {
		return nowBalanceRate;
	}

	public void setNowBalanceRate(Double nowBalanceRate) {
		this.nowBalanceRate = nowBalanceRate;
	}

	public Double getRmbmoney() {
		return (this.getBalancemoney()*this.getBalancerate()-getNowBalanceRate()*this.getProtestFee());
	}

	public void setRmbmoney(Double rmbmoney) {
		this.rmbmoney = rmbmoney;
	}

	public int getNoTuikuanNumberall() {
		return noTuikuanNumberall;
	}

	public void setNoTuikuanNumberall(int noTuikuanNumberall) {
		this.noTuikuanNumberall = noTuikuanNumberall;
	}

	public Double getNoTuiKuanMoneyall() {
		return noTuiKuanMoneyall;
	}

	public void setNoTuiKuanMoneyall(Double noTuiKuanMoneyall) {
		this.noTuiKuanMoneyall = noTuiKuanMoneyall;
	}

	public Double getTuiKuanMoneyall() {
		return tuiKuanMoneyall;
	}

	public void setTuiKuanMoneyall(Double tuiKuanMoneyall) {
		this.tuiKuanMoneyall = tuiKuanMoneyall;
	}

	public int getTuiKuanNumberall() {
		return tuiKuanNumberall;
	}

	public void setTuiKuanNumberall(int tuiKuanNumberall) {
		this.tuiKuanNumberall = tuiKuanNumberall;
	}

	public Long getMerchChnal() {
		return merchChnal;
	}

	public void setMerchChnal(Long merchChnal) {
		this.merchChnal = merchChnal;
	}

	public Long getRateID() {
		return rateID;
	}

	public void setRateID(Long rateID) {
		this.rateID = rateID;
	}
//未结算交易笔数
	/*未划款部分退款审核已通过		
	 * 	未划款全额退款		
	 * 	未划款拒付		
	 * 	未划款未退款未冻结未拒付已提交审核通过			
	 * 
	 * 
	 */
	public int getTradeNumberAll() {
		
		return this.noTuikuanNumberall+this.noProtestNumber+tradeNumber-this.refuce;
	}

	public void setTradeNumberAll(int tradeNumberAll) {
		this.tradeNumberAll = tradeNumberAll;
	}
//未划款金额
	public Double getTradeMoneyAll() {
		//return (this.noTuiKuanMoney+this.noTuiKuanMoneyall+noProtestMoney+this.tradeMoney-refuceMoney);
		return (this.noTuiKuanMoneyall+noProtestMoney+this.tradeMoney-refuceMoney);
	}

	public void setTradeMoneyAll(Double tradeMoneyAll) {
		this.tradeMoneyAll = tradeMoneyAll;
	}

	public int getRefuce() {
		return refuce;
	}

	public void setRefuce(int refuce) {
		this.refuce = refuce;
	}

	public Double getRefuceMoney() {
		return refuceMoney;
	}

	public void setRefuceMoney(Double refuceMoney) {
		this.refuceMoney = refuceMoney;
	}

	public int getRefuceComplement() {
		return refuceComplement;
	}

	public void setRefuceComplement(int refuceComplement) {
		this.refuceComplement = refuceComplement;
	}

	public Double getRefuceComplementMoney() {
		return refuceComplementMoney;
	}

	public void setRefuceComplementMoney(Double refuceComplementMoney) {
		this.refuceComplementMoney = refuceComplementMoney;
	}

	public Double getRefuceMoneyAll() {
		return refuceMoneyAll;
	}

	public void setRefuceMoneyAll(Double refuceMoneyAll) {
		this.refuceMoneyAll = refuceMoneyAll;
	}

	public Double getRefuceComplementMoneyAll() {
		return refuceComplementMoneyAll;
	}

	public void setRefuceComplementMoneyAll(Double refuceComplementMoneyAll) {
		this.refuceComplementMoneyAll = refuceComplementMoneyAll;
	}

	public Double getNothawMoney() {
		return nothawMoney;
	}

	public void setNothawMoney(Double nothawMoney) {
		this.nothawMoney = nothawMoney;
	}

	public int getNothawNumber() {
		return nothawNumber;
	}

	public void setNothawNumber(int nothawNumber) {
		this.nothawNumber = nothawNumber;
	}

	public Double getYesthawMoney() {
		return yesthawMoney;
	}

	public void setYesthawMoney(Double yesthawMoney) {
		this.yesthawMoney = yesthawMoney;
	}

	public int getYesthawNumber() {
		return yesthawNumber;
	}

	public void setYesthawNumber(int yesthawNumber) {
		this.yesthawNumber = yesthawNumber;
	}

}